CondoMAXium/package-lock.json, CondoMAXium/package.json, CondoMAXium/src/App.tsx, CondoMAXium/src/components/login.tsx, CondoMAXium/src/components/signup.tsx, CondoMAXium/src/main.tsx, CondoMAXium/tsconfig.json
=> implementation login/signup + clean up (pkg & App)

CondoMAXium/pages/add-property/index.js, CondoMAXium/pages/login/index.js, CondoMAXium/pages/signup/index.js
=> Backend after transfer

CondoMAXium/pages/profile-form/index.js, CondoMAXium/pages/profile/index.js, CondoMAXium/pages/reservation/index.js, CondoMAXium/pages/units/index.js, CondoMAXium/styles/profile.module.css, CondoMAXium/styles/profileForm.module.css, CondoMAXium/styles/reservation.module.css, CondoMAXium/styles/units.module.css
fixed css file connections
added profile form page
=> fixing css file connection and adding profile form page

CondoMAXium/pages/maintenance-reservation/index.js, CondoMAXium/test/addProperty.js, CondoMAXium/test/dashboard.js, CondoMAXium/test/maintenanceReservation.jsx
I did the maintenance-reservation, maintenanceReservation.jsx, dashboard.jsx, and addProperty.jsx pages. The branch is called user-reservation but should be called instead maintenance-reservation.
=> Maintenance Reservation

CondoMAXium/pages/add-unit/index.js, CondoMAXium/pages/edit-unit/index.js, CondoMAXium/pages/units/index.js, CondoMAXium/test/add-unit.test.js, CondoMAXium/test/edit-unit.test.js, CondoMAXium/test/units.test.js
Testing done on all unit related pages: add-unit, edit-unit and units
all lines covered but testing supabase is quite difficult, did as much as i could
also improved the editing and adding of properties to be more dynamic and work better with backend
also improved the styling of the buttons and fixed the search filter in units dashboard
=> Testing on units pages completed

CondoMAXium/styles/units.module.css
forgot to add this file in the previous pull request
=> css file change, forgot to be added

CondoMAXium/pages/dashboard/index.js, CondoMAXium/pages/dashboardCMC/index.js, CondoMAXium/pages/login/index.js
I implemented the backend logic for the following pages:
- dashboard 
- dashboardCMC
- login
Details:
- However, dashboard doesn't work completely. 
- DashboardCMC is being pushed for Financial system implementation.
- Modify the redirect path of the login page depending on the type of user.
=> Backend facu anass

CondoMAXium/pages/add-unit/index.js, CondoMAXium/pages/profile/index.js, CondoMAXium/pages/reset-password/index.js, CondoMAXium/pages/signup/index.js, CondoMAXium/pages/user-verification/index.js, CondoMAXium/test/signup.test.js
=> Sign up using code

CondoMAXium/pages/dashboardCMC/index.js, CondoMAXium/pages/view-property/index.js
This request is to add the view-properties page for CMC to the previously implemented view-units. Both of these are financial features of our app.
=> Properties financial info

CondoMAXium/pages/add-employee/index.js, CondoMAXium/pages/edit-employee/index.js, CondoMAXium/pages/manage-employees/index.js
- Created logic for managing employees
- Takes information from employees database and displays it
- Allows users to add an employee with these fields: first name, last name, email, phone number, and position
- Two positions: Financial analyst and Daily Operations Analyst (manager counts as CMC)
- Checks if email is already in the table
- Edit employee function: allows to change employee fields for an employee in the table
=> Manage, add and edit employees

CondoMAXium/pages/reset-password/index.js, CondoMAXium/pages/user-verification/index.js, CondoMAXium/test/reset-password.test.js, CondoMAXium/test/user-verification.test.js
The page now catch the 409 and 403 errors correctly.
=> Addition to testing of user-verification and reset-password files

CondoMAXium/pages/view-property/index.js, CondoMAXium/test/edit-unit.test.js, CondoMAXium/test/units.test.js, CondoMAXium/test/view-property.test.js, CondoMAXium/test/view-unit.test.js
- Improved the testing on view-units
- improved the testing on units page
- added the testing file for view-property
=> improvement of testing coverage for units and finance

CondoMAXium/pages/dashboardCMC/index.js
This pr will fix the #58 issue created with the double import of the UseRouter React Hook.
=> Deployment issue through UseRouter hook error

CondoMAXium/.eslintrc.json, CondoMAXium/pages/dashboardCMC/index.js, CondoMAXium/pages/form-gym/index.js, CondoMAXium/pages/form-rooftop-deck/index.js, CondoMAXium/pages/form-spa/index.js, CondoMAXium/pages/login/index.js, CondoMAXium/pages/requests-cmc/index.js
adding the french language to the login page
=> Testing language addition

CondoMAXium/pages/login/index.js, CondoMAXium/pages/profile/index.js
fixed errors and  attempt to see results on live version (main).
=> Language translation of the website

CondoMAXium/pages/add-employee/index.js, CondoMAXium/pages/add-property/index.js, CondoMAXium/pages/add-request/index.js, CondoMAXium/pages/add-unit/index.js, CondoMAXium/pages/dashboard/index.js, CondoMAXium/pages/dashboardCMC/index.js, CondoMAXium/pages/edit-employee/index.js, CondoMAXium/pages/edit-unit/index.js, CondoMAXium/pages/form-gym/index.js, CondoMAXium/pages/form-rooftop-deck/index.js, CondoMAXium/pages/form-spa/index.js, CondoMAXium/pages/maintenance-reservation/index.js, CondoMAXium/pages/manage-employees/index.js, CondoMAXium/pages/profile-form/index.js, CondoMAXium/pages/requests-cmc/index.js, CondoMAXium/pages/requests/index.js, CondoMAXium/pages/reservation/index.js, CondoMAXium/pages/reset-password/index.js, CondoMAXium/pages/signup/index.js, CondoMAXium/pages/units/index.js, CondoMAXium/pages/user-verification/index.js, CondoMAXium/pages/view-property/index.js, CondoMAXium/pages/view-unit/index.js
all pages are now linked to AI translator on SmartCat and allow for change of language on every page
=> all pages linked to translator

CondoMAXium/pages/dashboard/index.js, CondoMAXium/pages/dashboardCMC/index.js, CondoMAXium/pages/notifications-cmc/index.js, CondoMAXium/pages/notifications/index.js, CondoMAXium/test/notifications-cmc.test.js, CondoMAXium/test/notifications.test.js
- Notifications page for all users to view their requests
- Notifications-cmc page to view all users requests
- Tests for both notifications and notifications-cmc pages
- Linked notifications pages to the dashboards
=> User notification

CondoMAXium/.eslintrc.json, CondoMAXium/package-lock.json, CondoMAXium/package.json, CondoMAXium/pages/dashboard/index.js
Lint parser was not registering so i added a babel parser which fixed the issue
=> Fixed Deployment Issues

CondoMAXium/pages/add-property/index.js, CondoMAXium/pages/add-request/index.js, CondoMAXium/pages/requests-cmc/index.js, CondoMAXium/pages/requests/index.js, CondoMAXium/test/add-request.test.js, CondoMAXium/test/addProperty.test.js, CondoMAXium/test/dashboard.test.js, CondoMAXium/test/login.test.js, CondoMAXium/test/request-cmc.test.js, CondoMAXium/test/request.test.js
Improved testing on a lot of pages (add property, dashboard, all request pages)
did not change anything else in the pages
=> Testing80 lache

CondoMAXium/pages/requests-cmc/index.js, CondoMAXium/pages/requests/index.js
box tag not closing 
unused functions creating issues
resolved conflicts created other issues
=> Deployment issues
